//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.AccesoAdatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasoEmpleadoAsignado
    {
        public int Id { get; set; }
        public int IdCasos { get; set; }
        public int IdEmpleados { get; set; }
    }
}
