//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.AccesoAdatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Casos
    {
        public int Id { get; set; }
        public string DescripcionProblema { get; set; }
        public int Nivel { get; set; }
        public int Estado { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaResolucion { get; set; }
        public string ObservacionesResolucion { get; set; }
        public string NombreContacto { get; set; }
        public string TelefonoContacto { get; set; }
        public string DireccionContacto { get; set; }
        public int ProvinciaContacto { get; set; }
        public System.DateTime FechaInicioProceso { get; set; }
        public string MotivoRechazo { get; set; }
        public string DescripcionResolucion { get; set; }
    }
}
