//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.AccesoAdatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HelpDeskDBEntities : DbContext
    {
        public HelpDeskDBEntities()
            : base("name=HelpDeskDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CasoEmpleadoAsignado> CasoEmpleadoAsignado { get; set; }
        public virtual DbSet<Casos> Casos { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
